{% set version = "0.8-31" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-exactranktests
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/exactRankTests_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/exactRankTests/exactRankTests_{{ version }}.tar.gz
  sha256: fca19ef48fb50b9770d24d4b36715b889e6e57d2f8a0dbaa82d28e16d96ca484

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('exactRankTests')"           # [not win]
    - "\"%R%\" -e \"library('exactRankTests')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=exactRankTests
  license: GPL (>= 2)
  summary: Computes exact conditional p-values and quantiles using an implementation of the Shift-Algorithm
    by Streitberg & Roehmel.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: exactRankTests
# Title: Exact Distributions for Rank and Permutation Tests
# Date: 2019-04-29
# Version: 0.8-30
# Authors@R: c(person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org"), person("Kurt", "Hornik", role = "aut"))
# Description: Computes exact conditional p-values and quantiles using an implementation of the Shift-Algorithm by Streitberg & Roehmel.
# Depends: R (>= 2.4.0), stats, utils
# Suggests: survival
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2019-04-28 15:56:28 UTC; hothorn
# Author: Torsten Hothorn [aut, cre], Kurt Hornik [aut]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-04-28 19:20:12 UTC
