travis:
  secure:
    BINSTAR_TOKEN: pVVh6pxWJ8DMguVzxfojYQsypX5v9CxlNlb79vn6WmLS+4zoWj51VlZwlesI09DQvoBLTU6EMPdgxQ1AtPSczc816pk+zXiiUUyq0aXa5DxcJPMLEUyzXubvorjdSWVoWeYyRZys15s857D+R46PsChhrW/iMkVUklFCjP9DaAb0++Jl/K0w6x0mQBBbu4HTCBKHY1SS/Nyv7gXCH+AitC3UfA0querEj5+O5pkqxpnzhxszh+mVNGxYqYgBLqWio1qoSH7lx8OL1RjOsWWSfnT82R62p2SniRXjysCrA2YD+EWL3l12SVh4BBSeSzQM5PIXQ1eyAWviktjTcjQDW/VaQqpPd9ZQTIgoWTP3zhBX4mg9vazcIOao0WLVqYqDAoVNc1r97MtZXASm7296ny1IWfF7VDFfWJfxTLO8z/ydpNBXdSj1ByiANEv48sGIGB/iH2VgrjjMur77gGIy6SRR2BzMWbaLXT2VmaGPeTgvAAHcyDxOuKH1knCd6RlouViOYBwn+vaKyTxdii+dmN2aBqavb7wAopua2o3MIKcFChUGfkpJlqZWMDIYFC+dYxhkMNdCvpf5JdPTfr6fop02XR1sGLvU3kqLTYisfMT+F7sfVtMl2XnkaVrtriWJoZh1dPdgCnQzbvnlrbHNRO/95OqZ6MG7oX2EwLVeVKU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
