appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: SNUr1fWi6ia/jQJrHkA9IHvgm7YNbaeL9fVEeBmpc6FMrnkh7JQOR+aNSTOvLYW3211wo/eBeK3ubW6WxK001eOo47sYyVsyA+N8xmQB4ywbBpUgjEcDzKopqR9YX0RH3q+0R7dOQ58ESf/JJH7eGaqs2u29NbHCLhg4L8vcsKZiPAEByWql4810KfkLAYXHNQDrcBSagdKW7c02eJVs9qe7RBPIo26X2S1awOYYPzO9LfWN/Zy4seobaK5QVRxD3ZCWcXT9RdUhf6Xby/KHTS1pz2nJSXWoZe2PPfwYkNY2Ja5g+hl6Pf09srr+fiuSFddnA0nz9p3XEWTrj2Ppw8cbttR7x7BvMUZ38sBCCc6yXK6QL9Tb/QAjQll6xzPpGcb07vr5RqmUHV7HdEtXlxsKH7Dr/u10xKil3cuOTJX36ZjdXcEMQjwq+QFcWDTA8vwwYqvvs9DvwpuhNlu0QLuNHJ9V481QkSoD60808TUksZ8baFxcQGMCSkfuC9oz0lESQrrzgElZKk2FnD1mpOXX2iI3anZQ+b2TwrYP3070kDfribypSqw0VjNdo6UK6GK897/mzfL1LkadOx/KUgeGhVCbm9dgTtERmxcTEsOKWhQJOfT/9ox/UVhq5gwuGTTCve88AwXo0ZWW4hpMsjb8teY/Ex/KWfOFgeeXBtM=
